os:
  - linux

language: php

php:
  - '7.3'
  - '8.1'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  
script:
  - vendor/bin/phpunit --coverage-text